CREATE TABLE slider_images(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	path VARCHAR(255) NOT NULL,
	title VARCHAR(255) NULL,
	description VARCHAR(255) NULL,
	active BOOLEAN DEFAULT false,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
